# Generated by Django 5.1.3 on 2024-11-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0003_remove_memory_photo_remove_memory_video_memoryphoto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoryvideo',
            name='memory',
        ),
        migrations.AddField(
            model_name='memory',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='memory',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.DeleteModel(
            name='MemoryPhoto',
        ),
        migrations.DeleteModel(
            name='MemoryVideo',
        ),
    ]
