# Generated by Django 5.1.3 on 2024-11-30 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0004_remove_memoryvideo_memory_memory_photo_memory_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='video',
        ),
        migrations.CreateModel(
            name='MemoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='memory.memory')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='memory.memory')),
            ],
        ),
    ]
