# Generated by Django 5.1.3 on 2024-11-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0006_remove_memoryvideo_memory_memory_photo_memory_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
