# Generated by Django 5.1.3 on 2024-12-01 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0007_memory_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='created_at',
        ),
    ]
