# Generated by Django 5.1.3 on 2024-12-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0010_alter_memory_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
