# Generated by Django 5.1.3 on 2024-12-01 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0014_alter_memory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
